name: Autograde Swift Assignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Swift
      uses: swiftdocker/swift-docker-action@v1
      with:
        swift-version: '5.8' # Specify the required Swift version

    - name: Run tests
      run: swift test
