name: Autograde Swift Assignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Swift in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace swift:5.8 swift test
